from enum import Flag, auto

class ESTUDO_TYPE(Flag):
    INTERFERENCIA = auto()
    OPCAO = auto()

class WORK_ACTIVITY(Flag):        
    INTERFERENCIA_REQUERIMENTO_PESQUISA = auto()
    INTERFERENCIA_REQUERIMENTO_LICENCIAMENTO = auto()
    INTERFERENCIA_REQUERIMENTO_PLG = auto()    
    INTERFERENCIA_REQUERIMENTO_REGISTRO_EXTRAÇÃO = auto()    
    INTERFERENCIA_REQUERIMENTO_EDITAL = auto()        
    INTERFERENCIA_REQUERIMENTO_EDITAL_DAD = auto()        
    FORMULARIO_1_DIREITO_RLAVRA = auto()        
    OPCAO_REQUERIMENTO = auto()  # opção de área na fase de requerimento  
    INTERFERENCIA_GENERICO_NOT_EDITAL = INTERFERENCIA_REQUERIMENTO_PLG | INTERFERENCIA_REQUERIMENTO_LICENCIAMENTO | INTERFERENCIA_REQUERIMENTO_PESQUISA  
    INTERFERENCIA_GENERICO = INTERFERENCIA_GENERICO_NOT_EDITAL | INTERFERENCIA_REQUERIMENTO_EDITAL
    INTERFERENCIA_REQUERIMENTO_MUDANCA_REGIME = auto()
    INTERFERENCIA_REQUERIMENTO_RESTUDO = auto()



        