from enum import Flag, auto

class ESTUDO_TYPE(Flag):
    INTERFERENCIA = auto()
    OPCAO = auto()

class WORK_ACTIVITY(Flag):        
    INTERFERENCIA_REQUERIMENTO_PESQUISA = auto()
    INTERFERENCIA_REQUERIMENTO_LICENCIAMENTO = auto()
    INTERFERENCIA_REQUERIMENTO_PLG = auto()    
    INTERFERENCIA_REQUERIMENTO_REGISTRO_EXTRAÇÃO = auto()    
    INTERFERENCIA_REQUERIMENTO_EDITAL = auto()            
    INTERFERENCIA_GENERICO_REQUERIMENTO = (INTERFERENCIA_REQUERIMENTO_PESQUISA | 
                                           INTERFERENCIA_REQUERIMENTO_LICENCIAMENTO |
                                           INTERFERENCIA_REQUERIMENTO_PLG | 
                                           INTERFERENCIA_REQUERIMENTO_REGISTRO_EXTRAÇÃO |
                                           INTERFERENCIA_REQUERIMENTO_EDITAL)         
    INTERFERENCIA_FORMULARIO_1_DIREITO_REQUERER_LAVRA = auto()    
    INTERFERENCIA_GENERICO = (INTERFERENCIA_REQUERIMENTO_PESQUISA | 
                              INTERFERENCIA_REQUERIMENTO_LICENCIAMENTO |
                              INTERFERENCIA_REQUERIMENTO_PLG | 
                              INTERFERENCIA_REQUERIMENTO_REGISTRO_EXTRAÇÃO |
                              INTERFERENCIA_REQUERIMENTO_EDITAL |
                              INTERFERENCIA_FORMULARIO_1_DIREITO_REQUERER_LAVRA)       
    INTERFERENCIA_REQUERIMENTO_MUDANCA_REGIME = auto()
    INTERFERENCIA_REQUERIMENTO_RESTUDO = auto()
    OPCAO_REQUERIMENTO = auto()  # opção de área na fase de requerimento  
    ARQUIVAMENTO_ERRO_REPEM = auto()
    ARQUIVAMENTO_EDITAL_DAD = auto()        



        