from enum import Flag, auto

class ESTUDO_TYPE(Flag):
    INTERFERENCIA = auto()
    OPCAO = auto()

class WORK_ACTIVITY(Flag):        
    REQUERIMENTO_PESQUISA = auto()
    REQUERIMENTO_LICENCIAMENTO = auto()
    REQUERIMENTO_PLG = auto()    
    REQUERIMENTO_REGISTRO_EXTRAÇÃO = auto()    
    REQUERIMENTO_EDITAL = auto()
    REQUERIMENTO_EDITAL_DAD = auto() # old process to archive 
    REQUERIMENTO_OPCAO_ALVARA = auto()  # opção de área na fase de requerimento  
    DIREITO_RLAVRA_FORMULARIO_1 = auto()        
    REQUERIMENTO_GENERICO_NOT_EDITAL = REQUERIMENTO_PLG | REQUERIMENTO_LICENCIAMENTO | REQUERIMENTO_PESQUISA  
    REQUERIMENTO_GENERICO = REQUERIMENTO_GENERICO_NOT_EDITAL | REQUERIMENTO_EDITAL
    REQUERIMENTO_MUDANCA_REGIME = auto()
    REQUERIMENTO_RESTUDO = auto()

requerimentos_names = {
    WORK_ACTIVITY.REQUERIMENTO_PESQUISA: "Requerimento de Pesquisa",
    WORK_ACTIVITY.REQUERIMENTO_LICENCIAMENTO: "Requerimento de Licenciamento",
    WORK_ACTIVITY.REQUERIMENTO_PLG: "Requerimento de PLG",
    WORK_ACTIVITY.REQUERIMENTO_REGISTRO_EXTRAÇÃO: "Requerimento de Registro Extração"   
    # WORK_ACTIVITY.REQUERIMENTO_EDITAL_DAD: "Requerimento Edital DAD",
    # WORK_ACTIVITY.REQUERIMENTO_OPCAO_ALVARA: "Requerimento Opção Alvará",
    # WORK_ACTIVITY.DIREITO_RLAVRA_FORMULARIO_1: "Direito Rlavra Formulário 1",
    # WORK_ACTIVITY.REQUERIMENTO_GENERICO_NOT_EDITAL: "Requerimento Genérico (not Edital)",
    # WORK_ACTIVITY.REQUERIMENTO_GENERICO: "Requerimento Genérico",
    # WORK_ACTIVITY.REQUERIMENTO_MUDANCA_REGIME: "Requerimento Mudança Regime",
    # WORK_ACTIVITY.REQUERIMENTO_RESTUDO: "Requerimento Restudo"
}